#!/bin/sh

for battery in /sys/class/power_supply/BAT?*; do
    [ -n "$capacity" ] && printf " "

    capacity=$(cat "$battery/capacity" 2>/dev/null)

    if [ "$capacity" -gt 100 ]; then
        status=" "
    elif [ "$capacity" -gt 75 ]; then
        status=" "
    elif [ "$capacity" -gt 50 ]; then
        status=" "
    elif [ "$capacity" -gt 20 ]; then
        status=" "
    else
        status=" "
    fi

    printf "%s%s%%\n" "$status" "$capacity"
done
