#!/usr/bin/env bash

case "${BLOCK_BUTTON:-}" in
    1) kitty -e btop ;;
    6) kitty -e "$EDITOR" "$0" ;;
esac

memory_usage=$(free -h | awk '/^Mem/ { print $3"/"$2 }' | sed 's/i//g' | sed 's/,/./g')

echo "$memory_usage"