#!/bin/sh

getvol() {
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}'
}

ismuted() {
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED
}

case "$BLOCK_BUTTON" in
4)
    if ! ismuted; then
        v=$(getvol)
        nv=$((v + 2))
        [ "$nv" -gt 100 ] && nv=100
        wpctl set-volume @DEFAULT_AUDIO_SINK@ "$nv%"
    fi
    ;;
5)
    if ! ismuted; then
        v=$(getvol)
        nv=$((v - 2))
        [ "$nv" -lt 0 ] && nv=0
        wpctl set-volume @DEFAULT_AUDIO_SINK@ "$nv%"
    fi
    ;;
2)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    ;;
esac

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

echo "$vol" | grep -q MUTED && {
    echo ""
    exit
}

v=$(echo "$vol" | awk '{print int($2*100)}')

if [ "$v" -gt 40 ]; then
    icon=""
elif [ "$v" -gt 15 ]; then
    icon=""
else
    icon=""
fi

echo "$icon $v%"
