#!/bin/sh

INTERFACE="wlan0"
WIFI_INFO=$(iwctl station "$INTERFACE" show)

RAW_RSSI=$(printf "%s\n" "$WIFI_INFO" | grep 'RSSI' | grep -v 'Average' | awk '{print $2}')

case "$RAW_RSSI" in
  ''|*[!0-9-]*)
    {
      echo "------ $(date '+%F %T') -----"
      echo "iface: $INTERFACE"
      echo "ssid: ${SSID:-<empty>}"
      echo "raw_rssi: ${RAW_RSSI:-<empty>}"
      echo
      echo "[iwctl station show]"
      iwctl station "$INTERFACE" show 2>&1
      echo
      echo "[iw dev link]"
      iw dev "$INTERFACE" link 2>&1
      echo
      echo "[ip link]"
      ip link show "$INTERFACE" 2>&1
      echo
    } >> "$HOME/.wifi_debug.log"

    ICON="󰤫"
    printf "%s\n" "$ICON"
    exit 0
    ;;
esac

RSSI=$RAW_RSSI

if [ "$RSSI" -ge -50 ]; then
    ICON="󰤨"
elif [ "$RSSI" -ge -60 ]; then
    ICON="󰤥"
elif [ "$RSSI" -ge -70 ]; then
    ICON="󰤢"
elif [ "$RSSI" -ge -80 ]; then
    ICON="󰤟"
else
    ICON="󰤫"
fi

printf "%s\n" "$ICON"
