#!/usr/bin/env bash

update_status() {
    status=$(xset -q | grep LED)
    led_indicator=$(echo $status | awk '{ print substr($10, 5, 1) }')

    if [ "$led_indicator" -eq "1" ]; then
        echo "[RU]"
    else
        echo "[EN]"
    fi
}

toggle_lang() {
    status=$(xset -q | grep LED)
    led_indicator=$(echo $status | awk '{ print substr($10, 5, 1) }')

    if [ "$led_indicator" -eq "1" ]; then
        xkb-switch -s us
    else
        xkb-switch -s ru
    fi
}

case "${BLOCK_BUTTON:-}" in
    1) toggle_lang ;;
esac

update_status