#!/usr/bin/env bash

update_status() {
    status=$(xset -q | grep LED)
    led_indicator=$(echo $status | awk '{ print substr($10, 5, 1) }')

    PIDFILE="/tmp/recpid"

    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        prefix=""
    else
        prefix=" "
    fi

    if [ "$led_indicator" -eq "1" ]; then
        echo "${prefix}[RU]"
    else
        echo "${prefix}[EN]"
    fi
}

toggle_lang() {
    status=$(xset -q | grep LED)
    led_indicator=$(echo $status | awk '{ print substr($10, 5, 1) }')

    if [ "$led_indicator" -eq "1" ]; then
        xkb-switch -s us
    else
        xkb-switch -s ru
    fi
}

case "${BLOCK_BUTTON:-}" in
    1) toggle_lang ;;
esac

update_status
