#!/bin/sh

OFFSET_RE="\+([-0-9]+)\+([-0-9]+)"

X=$(xdotool getmouselocation | awk -F: '{print $2}' | awk '{print $1}')
Y=$(xdotool getmouselocation | awk -F: '{print $3}' | awk '{print $1}')

monitor_index=0
while read name width height xoff yoff
do
    if [ "${X}" -ge "$xoff" \
      -a "${Y}" -ge "$yoff" \
      -a "${X}" -lt "$(($xoff+$width))" \
      -a "${Y}" -lt "$(($yoff+$height))" ]
    then
        monitor=$name
        widthM=$width
        heightM=$height
        break
    fi
    ((monitor_index++))
done < <(xrandr | grep -w connected |
    sed -r "s/^([^ ]*).*\b([-0-9]+)x([-0-9]+)$OFFSET_RE.*$/\1 \2 \3 \4 \5/" |
    sort -nk4,5)

WID=$(xprop -root '_NET_ACTIVE_WINDOW' | grep --only-matching '0x.*')

WW=$(xwininfo -id "$WID" | awk '/Width:/ {print $2}')
WH=$(xwininfo -id "$WID" | awk '/Height:/ {print $2}')

SW=$widthM
SH=$heightM

wmctrl -r :ACTIVE: -e 2,$(((SW - WW)/2)),$(((SH - WH)/2)),"$WW","$WH"
