#!/bin/sh
rofi_command=(rofi -theme "$HOME/.config/rofi/powermenu.rasi")

lock=""
suspend="󰤄"
logout="󰗽"
reboot=""
shutdown="⏻"

chosen=$(printf '%s\n' "$lock" "$suspend" "$logout" "$reboot" "$shutdown" | "${rofi_command[@]}" -dmenu -selected-row 0)

case "$chosen" in
  "$lock") xset dpms force off ;;
  "$suspend") pkill -x mpv; systemctl suspend ;;
  "$logout") pkill dwm ;;
  "$reboot") systemctl reboot ;;
  "$shutdown") systemctl poweroff ;;
esac
