#! /bin/sh

nix_clean() {(
    home-manager expire-generations 0
    sudo nix-collect-garbage -d
    nix profile wipe-history
    nix store gc
    nix store optimise
)}

nix_clean &&

if [ $? -eq 0 ]; then
    notify-send "nix cleaned successfully"
    pw-play "$HOME/.local/media/soundeffect/minecraft-sheep2.mp3" &
else
    notify-send "nix cleaned failed"
    pw-play "$HOME/.local/media/soundeffect/minecraft-cave.mp3" &
fi
