#!/bin/sh
# script for create

read mon_w mon_h <<EOF
$(xrandr --query | awk '/\*/ { split($1,a,"x"); print a[1],a[2]; exit }' | sed 's/[^0-9 ]//g')
EOF

bar_h="$(
  xwininfo -root -tree |
    awk '/\("dwm" "dwm"\)/ {
      match($0, /[0-9]+x[0-9]+\+[0-9]+\+[0-9]+/)
      if (RSTART) {
        s = substr($0, RSTART, RLENGTH)
        split(s, a, /[x+]/)
        print a[2]
        exit
      }
    }'
)"

win_w=720
win_h=400

# если окно шире половины монитора
if [ "$win_w" -gt $((mon_w / 2)) ]; then
    x=-5-2
else
    x=$((mon_w - win_w - 5 - 2))
fi

y=$((mon_h - win_h - bar_h - 5 - 2))

if ! command -v dwm-msg >/dev/null 2>&1; then
    notify-send "dwm-ipc not installed" "dwm-msg command not found"
    exit 1
fi

dwm-msg run_command floatpos "${x}X ${y}Y ${win_w}W ${win_h}H"
