#!/usr/bin/env bash

_rofi () {
	rofi -no-auto-select -i "$@"
}

config_dir=${XDG_CONFIG_HOME:-$HOME/.config}
cache_dir=${XDG_CACHE_HOME:-$HOME/.cache}

notify='false'
clip=primary
clip_clear=45
clipboard_backend=${ROFI_PASS_CLIPBOARD_BACKEND:-xclip}

case "$clipboard_backend" in
	"xclip");;
	"wl-clipboard");;
	*)
		>&2 echo "Invalid clipboard backend '$clipboard_backend', falling back to xclip"
		clipboard_backend=xclip
		;;
esac

umask 077

_clip_in_primary_wl-clipboard()    { wl-copy -p; }
_clip_in_clipboard_wl-clipboard()  { wl-copy; }
_clip_out_primary_wl-clipboard()   { wl-paste -p; }
_clip_out_clipboard_wl-clipboard() { wl-paste; }
_clip_in_primary_xclip()           { xclip; }
_clip_in_clipboard_xclip()         { xclip -selection clipboard; }
_clip_out_primary_xclip()          { xclip -o; }
_clip_out_clipboard_xclip()        { xclip --selection clipboard -o; }

listgpg () {
	mapfile -d '' pw_list < <(find -L . -name '*.gpg' -print0)
	pw_list=("${pw_list[@]#./}")
	printf '%s\n' "${pw_list[@]}" | sort -n
}

list_passwords () {
	cd "${root}" || exit
	mapfile -t pw_list < <(listgpg)
	printf '%s\n' "${pw_list[@]%.gpg}" | sort -n
}

doClip () {
	case "$clip" in
		"primary")   ${clip_in_primary} ;;
		"clipboard") ${clip_in_clipboard} ;;
		"both")      ${clip_in_primary}; ${clip_out_primary} | ${clip_in_clipboard};;
	esac
}

checkIfPass () {
	printf '%s\n' "${root}: $selected_password" >| "$cache_dir/rofi-pass/last_used"
}

clearUp () {
	unset stuff
	unset password
	unset selected_password
	unset password_temp
	unset pass_content
}

showEntry () {
	declare -A stuff
	pass_temp=$(PASSWORD_STORE_DIR="${root}" pass show "$selected_password")
	password="${pass_temp%%$'\n'*}"
	pass_key_value=$(printf '%s\n' "${pass_temp}" | tail -n+2 | grep ': ')

	while read -r LINE; do
		[[ -z "$LINE" ]] && continue
		_id="${LINE%%: *}"
		_val="${LINE#* }"
		[[ -n "$_id" ]] && stuff["${_id}"]=${_val}
	done < <(printf '%s\n' "${pass_key_value}")

	stuff["pass"]=${password}

	pass_content="$(for key in "${!stuff[@]}"; do printf '%s\n' "${key}: ${stuff[$key]}"; done)"

	bla=$(printf '%s\n' "< Return" && printf '%s\n' "${!stuff[@]}" | sort \
		| _rofi -dmenu -mesg "Enter: Copy field to clipboard" -p "> ")
	rofi_exit=$?

	if [[ ${rofi_exit} -eq 1 ]]; then
		exit
	fi

	if [[ ${bla} == "< Return" ]]; then
		clearUp
		mainMenu
		return
	fi

	if [[ -z $(printf '%s' "${stuff[${bla}]}") ]]; then
		printf '%s' "$bla" | doClip
	else
		printf '%s' "${stuff[${bla}]}" | doClip
	fi

	if [[ $notify == "true" ]]; then
		notify-send "rofi-pass" "Copied\\nClearing in $clip_clear seconds"
	fi

	(sleep $clip_clear; printf '%s' "" | ${clip_in_primary}; printf '%s' "" | ${clip_in_clipboard}) &

	clearUp
	exit
}

mainMenu () {
	unset selected_password

	selected_password="$(list_passwords 2>/dev/null | _rofi -dmenu -p "> ")"
	rofi_exit=$?

	if [[ $rofi_exit -eq 1 ]]; then
		exit
	fi

	checkIfPass
	showEntry
	clearUp
}

get_config_file () {
	configs=("$ROFI_PASS_CONFIG"
		"$config_dir/rofi-pass/config"
		"/etc/rofi-pass.conf")

	for config in "${configs[@]}"; do
		if [[ -n "${config}" && -f "${config}" ]]; then
			printf "%s" "$config"
			return
		fi
	done
}

main () {
	config_file="$(get_config_file)"
	[[ -n "$config_file" ]] && source "$config_file"

	if [[ ! -d "$cache_dir/rofi-pass" ]]; then
		mkdir -p "$cache_dir/rofi-pass"
	fi

	clip_in_primary=_clip_in_primary_${clipboard_backend}
	clip_in_clipboard=_clip_in_clipboard_${clipboard_backend}
	clip_out_primary=_clip_out_primary_${clipboard_backend}
	clip_out_clipboard=_clip_out_clipboard_${clipboard_backend}

	if [[ -n ${PASSWORD_STORE_DIR} ]]; then
		root="${PASSWORD_STORE_DIR}"
	else
		root="$HOME/.password-store"
	fi

	export PASSWORD_STORE_DIR="${root}"

	mainMenu
}

main "$@"
