#!/bin/sh

sel=$(
    ps -eo pid,pgid,user,pcpu,pmem,cmd --sort=-pcpu --no-headers |
    rofi -dmenu -i -p "run" -lines 10 \
        -theme "$HOME/.config/rofi/rofi-pass.rasi" \
        -theme-str "window { width: 1280px; }"
) || exit 1

pgid=$(printf '%s\n' "$sel" | awk '{print $2}')

[ -n "$pgid" ] && kill -- "-$pgid"
