#!/bin/sh

pushd ~/HOME/infra/dotfiles
# sudo rm -rf $HOME/.mozilla/firefox/*/user.js &&
sudo nixos-rebuild --flake $HOME/HOME/infra/dotfiles#$whoami switch

if [ $? -eq 0 ]; then
    notify-send "nixos-rebuild switch completed successfully"
    pw-play "$HOME/.local/media/soundeffect/minecraft-sheep2.mp3" &
else
    notify-send "nixos-rebuild switch failed"
    pw-play "$HOME/.local/media/soundeffect/minecraft-cave.mp3" &
fi

popd
