#!/bin/sh

if nh clean all && nix profile wipe-history && nix store optimise
then
    notify-send -r 9991 "nix cleaned successfully"
    pw-play "$HOME/.local/media/soundeffect/minecraft-sheep2.mp3" &
else
    notify-send -r 9991 "nix cleaned failed"
    pw-play "$HOME/.local/media/soundeffect/minecraft-cave.mp3" &
fi
