#!/bin/sh
sudo nix flake update &&

if [ $? -eq 0 ]; then
    notify-send "nix-channel (system) update completed successfully"
    pw-play "$HOME/.local/media/soundeffect/minecraft-sheep2.mp3" &
else
    notify-send "nix-channel (system) update failed"
    pw-play "$HOME/.local/media/soundeffect/minecraft-cave.mp3" &
fi