#!/usr/bin/env bash

notify-send $BLOCK_BUTTON

case "$BLOCK_BUTTON" in
    1) kitty -e "$EDITOR" "$0" ;;
    4) notify-send 'yeah baby' ;;
    5) notify-send 'yeah baby' ;;
    6) notify-send 'yeah baby' ;;
esac

memory_usage=$(free -h | awk '/^Mem/ { print $3"/"$2 }' | sed 's/i//g' | sed 's/,/./g')

echo "$memory_usage"