#!/bin/sh
pushd ~/HOME/dotfiles
sudo nixos-rebuild switch -I nixos-config=$HOME/HOME/dotfiles/configuration.nix &&
notify-send "nixos-rebuild switch completed successfully" && 
paplay $HOME/.local/media/soundeffect/minecraft-sheep2.mp3
popd
