#!/bin/sh
# pushd ~/HOME/dotfiles
home-manager switch -f $HOME/HOME/dotfiles/home/home.nix &&

if [ $? -eq 0 ]; then
    notify-send "home-manager switch completed successfully"
    paplay "$HOME/.local/media/soundeffect/minecraft-sheep2.mp3" &
else
    notify-send "home-manager switch failed"
    paplay "$HOME/.local/media/soundeffect/minecraft-cave.mp3" &
fi

# popd
