#!/bin/sh
# pushd ~/HOME/dotfiles
home-manager switch -f $HOME/HOME/dotfiles/home/home.nix
notify-send "home-manager switch completed successfully" && 
paplay $HOME/.local/media/soundeffect/minecraft-sheep2.mp3
# popd
