# Xray reverse tunnel, config generated by lib/xray.nix.
#   portal: VPS, public VLESS+REALITY inbound, dokodemo-door for every port
#           that `exposeFrom` publishes in galaxy.expose.
#   bridge: jedha, dials the portals.
# Secrets come from sops as xray/<name>. Until they exist, `legacyConfig`
# keeps the old hand-written JSON in use.
{
  config,
  lib,
  pkgs,
  self,
  ...
}:

let
  inherit (lib) mkOption types;
  cfg = config.galaxy.services.xray;
  xrayLib = config.galaxy.lib.xray;

  generated =
    if cfg.role == "portal" then
      xrayLib.portal {
        inherit (cfg.portal)
          listen
          port
          dest
          serverNames
          users
          exposeListen
          ;
        expose = self.nixosConfigurations.${cfg.portal.exposeFrom}.config.galaxy.expose;
      }
    else
      xrayLib.bridge { inherit (cfg.bridge) portals; };

  template = pkgs.writeText "xray-template.json" (builtins.toJSON generated.config);

  render = pkgs.writeShellScript "xray-render" ''
    set -euo pipefail
    ${lib.getExe pkgs.jq} \
      ${
        lib.concatMapStringsSep " " (s: "--rawfile ${s} \"$CREDENTIALS_DIRECTORY/${s}\"") generated.secrets
      } \
      'walk(if type == "string" and startswith("@secret:") then $ARGS.named[.[8:-1]] | rtrimstr("\n") else . end)' \
      ${template} > "$RUNTIME_DIRECTORY/config.json"
  '';

  portal = types.submodule {
    options = {
      address = mkOption { type = types.str; };
      port = mkOption {
        type = types.port;
        default = 443;
      };
      serverName = mkOption { type = types.str; };
      publicKey = mkOption {
        type = types.str;
        description = "REALITY public key of the portal (not secret).";
      };
    };
  };
in
{
  options.galaxy.services.xray = {
    enable = lib.mkEnableOption "xray";

    legacyConfig = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Ready JSON config. When set, nothing is generated.";
    };

    role = mkOption {
      type = types.enum [
        "portal"
        "bridge"
      ];
      default = "portal";
    };

    portal = {
      listen = mkOption {
        type = types.str;
        default = "0.0.0.0";
      };
      port = mkOption {
        type = types.port;
        default = 443;
      };
      dest = mkOption {
        type = types.str;
        description = "REALITY target, e.g. \"www.example.com:443\".";
      };
      serverNames = mkOption { type = types.listOf types.str; };
      users = mkOption {
        type = types.listOf types.str;
        default = [ ];
        description = "Personal devices; each needs the secret xray/user_<name>.";
      };
      exposeFrom = mkOption {
        type = types.str;
        default = "jedha";
      };
      exposeListen = mkOption {
        type = types.str;
        default = "0.0.0.0";
      };
    };

    bridge.portals = mkOption {
      type = types.attrsOf portal;
      default = { };
      description = "Portals to dial, keyed by host name.";
    };
  };

  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      (lib.mkIf (cfg.legacyConfig != null) {
        services.xray = {
          enable = true;
          settingsFile = cfg.legacyConfig;
        };
      })

      (lib.mkIf (cfg.legacyConfig == null) {
        galaxy.sops.enable = lib.mkDefault true;

        sops.secrets = lib.genAttrs (map (s: "xray/${s}") generated.secrets) (_: {
          restartUnits = [ "xray.service" ];
        });

        services.xray = {
          enable = true;
          settingsFile = "/run/xray/config.json";
        };

        systemd.services.xray.serviceConfig = {
          RuntimeDirectory = "xray";
          RuntimeDirectoryMode = "0750";
          LoadCredential = map (s: "${s}:${config.sops.secrets."xray/${s}".path}") generated.secrets;
          ExecStartPre = [ render ];
        };
      })

      (lib.mkIf (cfg.role == "portal") {
        environment.systemPackages = [ pkgs.xray ];

        systemd.services.xray.serviceConfig = {
          RuntimeDirectory = "xray";
          RuntimeDirectoryMode = "0750";
          ReadWritePaths = [ "/run/xray" ];

          RuntimeMaxSec = "30min";
          Restart = "always";
        };
      })
    ]
  );
}
