return {
  "mason-org/mason-lspconfig.nvim",
  dependencies = {
    "mason-org/mason.nvim",
    "neovim/nvim-lspconfig",
  },
  -- lazy = false,
  -- event = "LspAttach",
  opts = {
    ensure_installed = {
      "lua_ls",
      "pyright",
      "ts_ls",
      "clangd",
      -- "cmake",
      "cssls",
      "dockerls",
      "gopls",
      "bashls",
      "html",
      "intelephense",
      "jsonls",
      "lemminx",
      "omnisharp",
      "rnix-lsp",
      "nixfmt",
      "nixpkgs-fmt",
      "sqlls",
      -- "taplo",
      -- "terraformls",
      "vimls",
      "yamlls",
    },
  },
}
