# good inspiration:
# https://github.com/ElysiaOS/ElysiaOS/blob/a9a624691fad67c27e213036d9b883272ca707f2/.zshrc
# https://github.com/BreadOnPenguins/dots/blob/master/.config/zsh/.zshrc
# https://github.com/manning390/nix-config/blob/59cfc956c77c1612a610c83f549e6bfa3e7f95b7/home/core/zsh/default.nix (starship setup on NixOS, plus other cool ideas, not my thing but interesting)

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# history
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
HISTDUP=erase

# powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# zsh plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

# add in snippets
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::command-not-found

# load completions
autoload -Uz compinit && compinit
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search

zinit cdreplay -q

# p10k
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# register plugins
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# opts
setopt autocd              # change directory just by typing its name
setopt magicequalsubst     # enable filename expansion for arguments of the form ‘anything=expression’
setopt nonomatch           # hide error message if there is no match for the pattern
setopt notify              # report the status of background jobs immediately
setopt numericglobsort     # sort filenames numerically when it makes sense
setopt promptsubst         # enable command substitution in prompt
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_find_no_dups
setopt appendhistory
setopt sharehistory

# bindkeys
bindkey -M viins '^[[1;5D' backward-word
bindkey -M viins '^[[1;5C' forward-word
bindkey -M viins '^[[D' backward-char
bindkey -M viins '^[[C' forward-char
bindkey '^?' backward-delete-char
bindkey '^H' backward-delete-char
bindkey '^f' autosuggest-accept
bindkey '^H' backward-kill-word
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down
bindkey '^[OA' up-line-or-beginning-search
bindkey '^[OB' down-line-or-beginning-search

# Completion styling
# zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
# zstyle ':completion:*' menu no
zstyle ":fzf-tab:*" use-fzf-default-opts yes
zstyle ":fzf-tab:complete:cd:*" fzf-preview "ls --color=always \${realpath}"

function _ps_aux_grep() { command ps aux | grep --color=auto "$1" }

alias ll='ls -lah --color'
alias la='ls -A --color'
alias psg='_ps_aux_grep'
alias ranger='yazi' # huh why not?

# Shell integrations
eval "$(fzf --zsh)"
