#!/bin/sh
xrandr --output HDMI-1-0 --scale 1x1 --mode 2560x1440 --rate 120.00 --right-of eDP-1
feh --geometry 3456x2160+0+0 --auto-zoom --bg-fill /home/dash/HOME/wizzard/wallpaper/game-of-thrones-kings-landing.png