# Appended to the config home-manager generates from services.picom
# (backend, vsync, fading, shadows, opacity). Don't repeat those keys here.

dbus = false;

# blur = {
#   method = "dual_kawase";
#   strength = 3;
#   size = 10;
# };
# blur-background = true;
# blur-background-frame = false;
# blur-background-fixed = false;
# blur-background-exclude = [
#   "class_g != 'kitty' && class_g != 'dmenu' && class_g != 'Rofi' && class_g != 'spterm'"
# ];

use-damage = true;

# Exclude dwm statusbar from focus detection so it doesn't affect focused/unfocused rules, (prevents bar/dmenu from interfering with opacity/fade logic)
# https://wiki.archlinux.org/title/Picom#dwm_and_dmenu
focus-exclude = "x = 0 && y = 0 && override_redirect = true";

unredir-if-possible = true;
unredir-if-possible-exclude = [ "class_g = 'mpv'", "class_g = 'librewolf'" ];

log-level = "warn";
show-all-xerrors = true;
