#!/bin/sh

# Получаем позицию мыши
X=$(xdotool getmouselocation | awk -F: '{print $2}' | awk '{print $1}')
Y=$(xdotool getmouselocation | awk -F: '{print $3}' | awk '{print $1}')

# Находим активный монитор
monitor_info=$(xrandr | grep -w connected | sed -r 's/^([^ ]+)[^0-9]*([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+).*/\1 \2 \3 \4 \5/')
active_monitor=""
active_w=0
active_h=0

while read name w h xoff yoff; do
    if [ "$X" -ge "$xoff" ] && [ "$X" -lt $(($xoff+$w)) ] && [ "$Y" -ge "$yoff" ] && [ "$Y" -lt $(($yoff+$h)) ]; then
        active_monitor=$name
        active_w=$w
        active_h=$h
        break
    fi
done <<EOF
$monitor_info
EOF

if [ -z "$active_monitor" ]; then
    echo "Не удалось определить активный монитор." >&2
    exit 1
fi

# Только для 2к монитора сбрасываем scale и dpi
if [ "${active_w}x${active_h}" = "2560x1440" ]; then
    export GDK_SCALE=1
    export GDK_DPI_SCALE=1
    export QT_AUTO_SCREEN_SCALE_FACTOR=0
    export QT_SCALE_FACTOR=1
    export QT_SCREEN_SCALE_FACTORS=1
    export MOZ_ENABLE_WAYLAND=1
    export XCURSOR_SIZE=24

    cmd="$1"
    shift
    cmd_name=$(basename "$cmd")
    
    case "$cmd_name" in
    spotify|code|discord|element-desktop)
        exec "$cmd" --force-device-scale-factor=1.5 "$@"
        ;;
    *)
        exec "$cmd" "$@"
        ;;
    esac
else
    exec "$@"
fi
