return {
	"xiyaowong/transparent.nvim",
	lazy = false,
	priority = 1001,
	opts = {
		enable = true,
		groups = {
			"Normal",
			"NormalNC",
			"NormalFloat",
		},
		exclude_groups = {
			"CursorLine",
			"CursorLineNr",
			"Visual",
			"VisualNOS",
			"Search",
			"IncSearch",
			"Pmenu",
			"PmenuSel",
			"StatusLine",
			"StatusLineNC",
			"WinSeparator",
			"SignColumn",
			"LineNr",
			"EndOfBuffer",
			"FoldColumn",
		},
	},
}
