#!/bin/sh

update_status() {
    status="$(xset -q | grep LED)"
    led_indicator="$(printf '%s\n' "$status" | awk '{ print substr($10, 5, 1) }')"

    PIDFILE="/tmp/recpid"

    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        prefix=""
    else
        prefix=" "
    fi

    if [ "$led_indicator" = "1" ]; then
        printf "%s[RU]\n" "$prefix"
    else
        printf "%s[EN]\n" "$prefix"
    fi
}

toggle_lang() {
    status="$(xset -q | grep LED)"
    led_indicator="$(printf '%s\n' "$status" | awk '{ print substr($10, 5, 1) }')"

    if [ "$led_indicator" = "1" ]; then
        xkb-switch -s us
    else
        xkb-switch -s ru
    fi
}

case "${BLOCK_BUTTON:-}" in
    1) toggle_lang ;;
esac

update_status
