#!/usr/bin/env bash
rofi_command=(rofi -theme "$HOME/.config/rofi/powermenu.rasi")

lock=""
suspend="󰤄"
logout="󰗽"
reboot=""
shutdown="⏻"

chosen=$(printf '%s\n' "$lock" "$suspend" "$logout" "$reboot" "$shutdown" | "${rofi_command[@]}" -dmenu -selected-row 0)

_clear() {
  rm -f ~/.cache/greenclip.history
}

case "$chosen" in
    "$lock") _clear; loginctl lock-session ;;
    "$suspend") _clear; pkill -x mpv; systemctl suspend ;;
    "$logout") _clear; loginctl kill-user "$USER" ;;
    "$reboot") _clear; systemctl reboot ;;
    "$shutdown") _clear; systemctl poweroff ;;
esac
